apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: foo 
  janus-idp.io/tekton: foo
  backstage.io/kubernetes-id: foo
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: foo
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml