apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: foo
  janus-idp.io/tekton: foo
  backstage.io/kubernetes-id: foo
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: foo
resources:
- deployment.yaml
- route.yaml
- service.yaml
